name: CI for karsajobs  # Descriptive name for your CI workflow

on:
  push:
    branches:
      - main  # Trigger the workflow only on pushes to the' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for this job

    steps:
      - name: Checkout Repository  # Checkout the Git repository
        uses: actions/checkout@v2

      - name: Install and Run Hadolint  # Install and run Hadolint to lint Dockerfile
        run: |
          wget -O hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x hadolint
          ./hadolint Dockerfile

      - name: Build and Push Docker Image  # Build and push a Docker image
        run: |
          export GH_TOKEN=${{ secrets.GH_TOKEN }}
          bash build_push_image_jadwal_api.sh